import type {
  ChecklistItem,
  TaskDocument,
  PlanTask,
  MasterPlanMilestone,
  DailyPlanEntry,
} from "@/types/planning";

/* ─── Checklist Items ──────────────────────────────────────── */

export const mockChecklist: ChecklistItem[] = [
  { id: "cl-1", text: "Phân tích yêu cầu nghiệp vụ và xác định scope", isCompleted: true },
  { id: "cl-2", text: "Thiết kế wireframe cho luồng chính", isCompleted: true },
  { id: "cl-3", text: "Viết API specification (OpenAPI 3.0)", isCompleted: true },
  { id: "cl-4", text: "Tạo database schema migration", isCompleted: false },
  { id: "cl-5", text: "Implement unit test cho service layer", isCompleted: false },
  { id: "cl-6", text: "Review và merge Pull Request", isCompleted: false },
];

/* ─── Documents ────────────────────────────────────────────── */

export const mockDocuments: TaskDocument[] = [
  {
    id: "doc-1",
    fileName: "PRD_AI_Planning_v2.1.pdf",
    fileType: "PDF",
    url: "#",
  },
  {
    id: "doc-2",
    fileName: "API_Specification.docx",
    fileType: "DOCX",
    url: "#",
  },
  {
    id: "doc-3",
    fileName: "UI_Mockup_Planning.fig",
    fileType: "FIGMA",
    url: "#",
  },
  {
    id: "doc-4",
    fileName: "Database_ERD_Diagram.png",
    fileType: "IMAGE",
    url: "#",
  },
  {
    id: "doc-5",
    fileName: "Confluence: Quy trình phát triển Sprint 4",
    fileType: "LINK",
    url: "#",
  },
];

/* ─── Single Full Task (for modal preview) ─────────────────── */

export const mockTask: PlanTask = {
  id: "tsk-ai-001",
  title: "Xây dựng module AI Planning — Backend API",
  status: "IN_PROGRESS",
  priority: "HIGH",
  assignee: "Nguyễn Minh Tuấn",
  description:
    "Thiết kế và triển khai REST API cho module AI Planning bao gồm: CRUD cho Master Plan, tự động sinh Daily Plan từ milestone, và tích hợp AI suggestion engine để đề xuất task hàng ngày dựa trên tiến độ thực tế của người dùng.",
  dueDate: "2026-08-25",
  category: "DEVELOPMENT",
  estimatedMinutes: 480,
  checklist: mockChecklist,
  documents: mockDocuments,
};

/* ─── Master Plan Milestones ───────────────────────────────── */

export const mockMasterPlanMilestones: MasterPlanMilestone[] = [
  {
    id: "ms-1",
    title: "Giai đoạn 1 — Nền tảng & Kiến trúc",
    description: "Thiết lập hạ tầng, CI/CD, database schema, và authentication module.",
    status: "COMPLETED",
    orderIndex: 0,
    progress: 100,
    tasks: [
      {
        id: "tsk-1-1",
        title: "Thiết kế kiến trúc hệ thống (System Design)",
        status: "COMPLETED",
        priority: "HIGH",
        assignee: "Trần Văn Hùng",
        description: "Xây dựng tài liệu kiến trúc tổng quan, chọn tech stack, và vẽ sơ đồ luồng dữ liệu.",
        dueDate: "2026-07-15",
        category: "ARCHITECTURE",
        estimatedMinutes: 240,
        checklist: [
          { id: "c1", text: "Vẽ architecture diagram", isCompleted: true },
          { id: "c2", text: "Chọn database (PostgreSQL)", isCompleted: true },
          { id: "c3", text: "Review với Tech Lead", isCompleted: true },
        ],
        documents: [
          { id: "d1", fileName: "System_Architecture_v1.pdf", fileType: "PDF", url: "#" },
        ],
      },
      {
        id: "tsk-1-2",
        title: "Cấu hình CI/CD Pipeline",
        status: "COMPLETED",
        priority: "MEDIUM",
        assignee: "Lê Thị Mai",
        description: "Setup GitHub Actions cho build, test, và deploy tự động lên staging.",
        dueDate: "2026-07-20",
        category: "DEVOPS",
        estimatedMinutes: 180,
        checklist: [
          { id: "c4", text: "Tạo Dockerfile", isCompleted: true },
          { id: "c5", text: "Cấu hình workflow YAML", isCompleted: true },
        ],
        documents: [],
      },
      {
        id: "tsk-1-3",
        title: "Implement Authentication & Authorization",
        status: "COMPLETED",
        priority: "HIGH",
        assignee: "Nguyễn Minh Tuấn",
        description: "JWT-based auth, role-based access control, refresh token flow.",
        dueDate: "2026-07-25",
        category: "DEVELOPMENT",
        estimatedMinutes: 360,
        checklist: [
          { id: "c6", text: "Implement JWT service", isCompleted: true },
          { id: "c7", text: "Tạo middleware xác thực", isCompleted: true },
          { id: "c8", text: "Viết integration test", isCompleted: true },
        ],
        documents: [
          { id: "d2", fileName: "Auth_Flow_Sequence.png", fileType: "IMAGE", url: "#" },
        ],
      },
    ],
  },
  {
    id: "ms-2",
    title: "Giai đoạn 2 — Core Features (MVP)",
    description: "Xây dựng các tính năng lõi: Master Plan CRUD, Daily Plan engine, và Task management.",
    status: "IN_PROGRESS",
    orderIndex: 1,
    progress: 58,
    tasks: [
      {
        ...mockTask,
        id: "tsk-2-1",
      },
      {
        id: "tsk-2-2",
        title: "Thiết kế UI/UX cho Planning Dashboard",
        status: "IN_PROGRESS",
        priority: "HIGH",
        assignee: "Phạm Hoàng Anh",
        description: "Thiết kế giao diện responsive cho trang tổng quan Planning với master plan timeline và daily view.",
        dueDate: "2026-08-22",
        category: "DESIGN",
        estimatedMinutes: 300,
        checklist: [
          { id: "c9", text: "Wireframe low-fi", isCompleted: true },
          { id: "c10", text: "High-fi mockup trên Figma", isCompleted: true },
          { id: "c11", text: "Prototype tương tác", isCompleted: false },
          { id: "c12", text: "Handoff cho dev team", isCompleted: false },
        ],
        documents: [
          { id: "d3", fileName: "Planning_UI_Mockup.fig", fileType: "FIGMA", url: "#" },
          { id: "d4", fileName: "Design_System_Tokens.xlsx", fileType: "SPREADSHEET", url: "#" },
        ],
      },
      {
        id: "tsk-2-3",
        title: "Tích hợp AI Suggestion Engine",
        status: "NOT_STARTED",
        priority: "MEDIUM",
        assignee: "Đỗ Quang Minh",
        description: "Kết nối với AI model để đề xuất task hàng ngày dựa trên learning pattern của user.",
        dueDate: "2026-08-30",
        category: "AI_INTEGRATION",
        estimatedMinutes: 420,
        checklist: [
          { id: "c13", text: "Research AI model options", isCompleted: false },
          { id: "c14", text: "Thiết kế prompt template", isCompleted: false },
          { id: "c15", text: "Implement suggestion API", isCompleted: false },
        ],
        documents: [
          { id: "d5", fileName: "AI_Research_Notes.docx", fileType: "DOCX", url: "#" },
        ],
      },
      {
        id: "tsk-2-4",
        title: "Viết test E2E cho luồng Planning",
        status: "NOT_STARTED",
        priority: "LOW",
        assignee: "Lê Thị Mai",
        description: "Playwright tests cho happy path: tạo plan → thêm task → check progress.",
        dueDate: "2026-09-05",
        category: "QA",
        estimatedMinutes: 240,
        checklist: [
          { id: "c16", text: "Setup Playwright project", isCompleted: false },
          { id: "c17", text: "Viết test scenario", isCompleted: false },
        ],
        documents: [],
      },
    ],
  },
  {
    id: "ms-3",
    title: "Giai đoạn 3 — Polish & Launch",
    description: "Tối ưu hiệu năng, hoàn thiện UX, và triển khai production.",
    status: "NOT_STARTED",
    orderIndex: 2,
    progress: 0,
    tasks: [
      {
        id: "tsk-3-1",
        title: "Performance Optimization & Caching",
        status: "NOT_STARTED",
        priority: "MEDIUM",
        assignee: "Trần Văn Hùng",
        description: "Redis caching, query optimization, lazy loading cho frontend.",
        dueDate: "2026-09-15",
        category: "OPTIMIZATION",
        estimatedMinutes: 300,
        checklist: [
          { id: "c18", text: "Profile bottleneck queries", isCompleted: false },
          { id: "c19", text: "Implement Redis cache layer", isCompleted: false },
          { id: "c20", text: "Frontend bundle splitting", isCompleted: false },
        ],
        documents: [],
      },
      {
        id: "tsk-3-2",
        title: "User Acceptance Testing (UAT)",
        status: "NOT_STARTED",
        priority: "HIGH",
        assignee: "Phạm Hoàng Anh",
        description: "Phối hợp với stakeholder để test tất cả user story trên staging.",
        dueDate: "2026-09-20",
        category: "QA",
        estimatedMinutes: 480,
        checklist: [
          { id: "c21", text: "Chuẩn bị test script", isCompleted: false },
          { id: "c22", text: "Thực hiện UAT round 1", isCompleted: false },
          { id: "c23", text: "Fix critical bugs", isCompleted: false },
          { id: "c24", text: "UAT round 2 — sign-off", isCompleted: false },
        ],
        documents: [
          { id: "d6", fileName: "UAT_Checklist_Template.xlsx", fileType: "SPREADSHEET", url: "#" },
        ],
      },
      {
        id: "tsk-3-3",
        title: "Production Deployment & Monitoring",
        status: "NOT_STARTED",
        priority: "URGENT",
        assignee: "Lê Thị Mai",
        description: "Deploy production, cấu hình monitoring (Datadog), và alerting.",
        dueDate: "2026-09-25",
        category: "DEVOPS",
        estimatedMinutes: 240,
        checklist: [
          { id: "c25", text: "Tạo production environment", isCompleted: false },
          { id: "c26", text: "Cấu hình Datadog APM", isCompleted: false },
          { id: "c27", text: "Setup alert rules", isCompleted: false },
        ],
        documents: [],
      },
    ],
  },
];

/* ─── Daily Plan Entries ───────────────────────────────────── */

export const mockDailyPlanEntries: DailyPlanEntry[] = [
  {
    id: "dp-1",
    date: "2026-08-18",
    availableMinutes: 480,
    totalPlannedMinutes: 420,
    tasks: [
      {
        id: "dpt-1",
        title: "Review PR #142 — Auth middleware refactor",
        status: "COMPLETED",
        priority: "HIGH",
        assignee: "Nguyễn Minh Tuấn",
        description: "Code review cho PR auth middleware, kiểm tra security edge cases.",
        dueDate: "2026-08-18",
        category: "REVIEW",
        estimatedMinutes: 60,
        checklist: [
          { id: "dc1", text: "Đọc mô tả PR", isCompleted: true },
          { id: "dc2", text: "Review logic xử lý", isCompleted: true },
          { id: "dc3", text: "Approve và merge", isCompleted: true },
        ],
        documents: [],
      },
      {
        id: "dpt-2",
        title: "Implement Master Plan CRUD endpoints",
        status: "IN_PROGRESS",
        priority: "HIGH",
        assignee: "Nguyễn Minh Tuấn",
        description: "REST API cho tạo, đọc, cập nhật, xóa Master Plan với validation đầy đủ.",
        dueDate: "2026-08-18",
        category: "DEVELOPMENT",
        estimatedMinutes: 240,
        checklist: [
          { id: "dc4", text: "GET /api/plans endpoint", isCompleted: true },
          { id: "dc5", text: "POST /api/plans endpoint", isCompleted: true },
          { id: "dc6", text: "PUT /api/plans/:id endpoint", isCompleted: false },
          { id: "dc7", text: "DELETE /api/plans/:id endpoint", isCompleted: false },
        ],
        documents: [
          { id: "dd1", fileName: "API_Spec_Planning.pdf", fileType: "PDF", url: "#" },
        ],
      },
      {
        id: "dpt-3",
        title: "Standup meeting & Sprint planning",
        status: "COMPLETED",
        priority: "MEDIUM",
        assignee: "Nguyễn Minh Tuấn",
        description: "Daily standup 15 phút + sprint planning cho tuần tiếp theo.",
        dueDate: "2026-08-18",
        category: "MEETING",
        estimatedMinutes: 60,
        checklist: [],
        documents: [],
      },
      {
        id: "dpt-4",
        title: "Viết unit test cho PlanService",
        status: "NOT_STARTED",
        priority: "MEDIUM",
        assignee: "Nguyễn Minh Tuấn",
        description: "Test coverage cho PlanService: create, update, delete, getByUser.",
        dueDate: "2026-08-18",
        category: "TESTING",
        estimatedMinutes: 60,
        checklist: [
          { id: "dc8", text: "Test createPlan()", isCompleted: false },
          { id: "dc9", text: "Test updatePlan()", isCompleted: false },
        ],
        documents: [],
      },
    ],
  },
  {
    id: "dp-2",
    date: "2026-08-19",
    availableMinutes: 480,
    totalPlannedMinutes: 360,
    tasks: [
      {
        id: "dpt-5",
        title: "Hoàn thiện PUT & DELETE endpoints",
        status: "NOT_STARTED",
        priority: "HIGH",
        assignee: "Nguyễn Minh Tuấn",
        description: "Hoàn thiện 2 endpoint còn lại từ ngày hôm qua.",
        dueDate: "2026-08-19",
        category: "DEVELOPMENT",
        estimatedMinutes: 180,
        checklist: [
          { id: "dc10", text: "PUT endpoint + validation", isCompleted: false },
          { id: "dc11", text: "DELETE endpoint + soft delete", isCompleted: false },
          { id: "dc12", text: "Integration test", isCompleted: false },
        ],
        documents: [],
      },
      {
        id: "dpt-6",
        title: "Thiết kế Daily Plan auto-generation logic",
        status: "NOT_STARTED",
        priority: "MEDIUM",
        assignee: "Nguyễn Minh Tuấn",
        description: "Viết tài liệu kỹ thuật cho thuật toán tự động sinh Daily Plan từ Master Plan.",
        dueDate: "2026-08-19",
        category: "ARCHITECTURE",
        estimatedMinutes: 120,
        checklist: [],
        documents: [],
      },
      {
        id: "dpt-7",
        title: "Sync với Design team về UI feedback",
        status: "NOT_STARTED",
        priority: "LOW",
        assignee: "Nguyễn Minh Tuấn",
        description: "Meeting 30 phút để align UI component với design tokens mới.",
        dueDate: "2026-08-19",
        category: "MEETING",
        estimatedMinutes: 60,
        checklist: [],
        documents: [
          { id: "dd2", fileName: "Design_Feedback_Notes.docx", fileType: "DOCX", url: "#" },
        ],
      },
    ],
  },
  {
    id: "dp-3",
    date: "2026-08-20",
    availableMinutes: 480,
    totalPlannedMinutes: 390,
    tasks: [
      {
        id: "dpt-8",
        title: "Implement Daily Plan auto-generation engine",
        status: "NOT_STARTED",
        priority: "HIGH",
        assignee: "Nguyễn Minh Tuấn",
        description: "Triển khai thuật toán sinh Daily Plan từ Master Plan milestones.",
        dueDate: "2026-08-20",
        category: "DEVELOPMENT",
        estimatedMinutes: 240,
        checklist: [
          { id: "dc13", text: "Parse milestone deadlines", isCompleted: false },
          { id: "dc14", text: "Distribute tasks by priority", isCompleted: false },
          { id: "dc15", text: "Respect daily time budget", isCompleted: false },
        ],
        documents: [],
      },
      {
        id: "dpt-9",
        title: "Code review session với team",
        status: "NOT_STARTED",
        priority: "MEDIUM",
        assignee: "Nguyễn Minh Tuấn",
        description: "Review code của team members cho sprint hiện tại.",
        dueDate: "2026-08-20",
        category: "REVIEW",
        estimatedMinutes: 90,
        checklist: [],
        documents: [],
      },
      {
        id: "dpt-10",
        title: "Viết documentation cho Planning API",
        status: "NOT_STARTED",
        priority: "LOW",
        assignee: "Nguyễn Minh Tuấn",
        description: "Swagger docs + README cho toàn bộ Planning module.",
        dueDate: "2026-08-20",
        category: "DOCUMENTATION",
        estimatedMinutes: 60,
        checklist: [],
        documents: [],
      },
    ],
  },
];
